version: '3.4'
services:

  rasa-server:
    image: rasa-bot:latest
    working_dir: /
    build: "./"
    restart: always
    volumes:
    - ./actions:/actions
    - ./data:/data
    command: bash -c "rm -rf models/* && rasa train --config config.yml && rasa run --enable-api --cors \"*\""
    ports:
    - '5006:5005'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /
    build: "./"
    restart: always
    volumes:
    - ./actions:/actions
    - ./utils:/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
